### ISSUE TITLE
how to build and run three-text2d/example/index.html

### ISSUE THREAD

**Issue by paul-shannon** [gamestdio/three-text2d#12]
I have been experimenting but so far without success.

    npm install  # learned module "three" not present.  
       # got that from github, npm installed it globally
    npm install # now works

Now trying to build bundle.js needed by examples/index.html:

     webpack --config webpack.dist.config.js 
      TypeError: this.ts.getAutomaticTypeDirectiveNames is not a function
        at State.loadTypesFromConfig (/Users/paul/github/three-text2d/node_modules/awesome-typescript-loader/src/host.ts:150:36)

I am probably missing the obvious.  Can you help?   If it is my ignorance of npm and webpack, a pointer to some references or tutorials would be most welcome

**Comment by endel** [comment]
Hi @paul-shannon, 

Sorry, it wasn't your fault. it wasn't really working. 
Now I've updated and it's back. Can you pull the changes, run `npm install` and `npm start` again?

Cheers!
