### ISSUE TITLE
main in package.json points to non-existent file

### ISSUE THREAD

**Issue by dflor003** [gamestdio/three-text2d#15]
I tried `npm install`ing the library and right after I import it into my project, I get file not found errors.

Upon further inspection, it seems that `package.json` has ` "main": "lib/index.js",` but there is no corresponding file there.

**Comment by endel** [comment]
Oops, my bad. Can you try again with version `0.3.2`?

**Comment by dflor003** [comment]
Seems to be working now! Thanks!
