### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by omarojo** [gamestdio/three-text2d#2]
Is there a way to set a background color box? like a tooltip.

something similar to the following.

```
        toolTipCanvas = document.createElement('canvas');
    toolTipContext = toolTipCanvas.getContext('2d');
    toolTipContext.font = "Bold 20px Arial";

       var message = "HELLO WORLD"; //book title
       var metrics = toolTipContext.measureText(message);
       var width = metrics.width;
       toolTipContext.fillStyle = "rgba(0,0,0,0.95)"; // black border
       toolTipContext.fillRect( 0,0, width+8,20+8);
       toolTipContext.fillStyle = "rgba(255,255,255,0.95)"; // white filler
       toolTipContext.fillRect( 2,2, width+4,20+4 );
       toolTipContext.fillStyle = "rgba(0,0,0,1)"; // text color
       toolTipContext.fillText( message, 4,20 );

    // canvas contents will be used for a texture
    toolTipTexture = new THREE.Texture(toolTipCanvas);
    toolTipTexture.needsUpdate = true;

    ////////////////////////////////////////

    var spriteMaterial = new THREE.SpriteMaterial( { map: toolTipTexture } );

    toolTipSprite = new THREE.Sprite( spriteMaterial );
    toolTipSprite.scale.set(200,100,1.0);
    toolTipSprite.position.set( 0, 0, 1 );
    sceneOrtho.add( toolTipSprite );
```

**Comment by endel** [comment]
Hi @omarojo,

You could achieve this by creating a regular rectangle at the same position of the text, and resizing it using the text's width and height.

**Comment by omarojo** [comment]
@endel but... do I need to modify your code for that to use the same canvas context when retrieving the Sprite ?

**Comment by endel** [comment]
@omarojo yes, this library currently doesn't support having background color. It just renders the text itself.

In case you would like to contribute by implementing this feature, you can find the class that deals with canvas here: https://github.com/gamestdio/three-text2d/blob/master/src/CanvasText.js - it might be a good idea to have a way to set the background "padding" as well.

Thanks!
