### ISSUE TITLE
do you have library without load module?

### ISSUE THREAD

**Issue by anakein** [gamestdio/three-text2d#25]
i want testing over old browser and this don´t work type=module.

**Comment by endel** [comment]
Hey @anakein, you can import the `dist` file directly on a `script` tag: https://github.com/gamestdio/three-text2d/tree/master/dist

**Comment by anakein** [comment]
and then console show this: ReferenceError: MeshText2D is not defined

**Comment by anakein** [comment]
i try import { MeshText2D, textAlign } from 'three-text2d' on my first line script but i have other error.
"Import declarations may only appear at top level of a module"

**Comment by axion014** [comment]
The IIFE is returning the module but that module isn't assigned anywhere and is being immediately discarded.
People who aren't using modules need to get the module on `window`.
Right now, only workarounds I can think of is to host edited source yourself, or `eval` the original bundle and assign it to a variable.
Neither looks good.

**Comment by endel** [comment]
@axion014 should've fixed this on his pull-request https://github.com/gamestdio/three-text2d/pull/28

the new dist file has been updated: https://github.com/gamestdio/three-text2d/tree/master/dist

thanks @axion014!
