### ISSUE TITLE
gh-pages not loading

### ISSUE THREAD

**Issue by russplaysguitar** [gamestdio/three-text2d#3]
"Uncaught TypeError: THREE.Spherical is not a constructor" on: http://gamestd.io/three-text2d/

**Comment by endel** [comment]
Hey @russplaysguitar, thanks for reporting! I've updated the to use latest three.js version and its working again.

Cheers!

**Comment by russplaysguitar** [comment]
Thanks!

**Comment by russplaysguitar** [comment]
And thanks for making this project, btw. I was looking into having to basically do the same thing in order to improve performance (rendering a lot of text), so this is saving me a lot of time.

**Comment by endel** [comment]
@russplaysguitar great! I'm glad this is saving you some time too. 

This library currently uploads a texture into the GPU for every Text2D instance created. In case you have performance issues using too many instances it might be a good idea to make this library reuse the same texture for all instances.

Thanks!
