### ISSUE TITLE
Probably noob issues installing the script

### ISSUE THREAD

**Issue by JoeriBultheel** [gamestdio/three-text2d#30]
Hi,

I'm sorry but I'm quite new to Javascript programming. How can I correctly use your script?

if this is my file structure:
- public/index.html
- public/js/player.js
- node_modules/three-text2d/dist/three-text2d.js

I reference the player.js script in my index.html with a <script type="module"> so the import statement will work. However I still get errors when trying to import the code inmy player.js as follows:

```
import { SpriteText2D, textAlign } from '../../node_modules/three-text2d/dist/three-text2d.js';

var User = function() {
    this.userID;
    this.userName;
```

```
three-text2d.js:9 Uncaught TypeError: Cannot read property 'THREE' of undefined
    at webpackUniversalModuleDefinition (three-text2d.js:9)
    at three-text2d.js:10
webpackUniversalModuleDefinition @ three-text2d.js:9
(anonymous) @ three-text2d.js:10
index.html:1 Uncaught SyntaxError: The requested module '../../node_modules/three-text2d/dist/three-text2d.js' does not provide an export named 'textAlign'
three.js:22137 THREE.WebGLRenderer 100
```

Do I need to compile your scripts? I just downloaded the zip and put them in my node_modules folder. ( I also ran 'npm install' in your root folder). Thank you!

**Comment by endel** [comment]
Hey @JoeriBultheel, I haven't tested loading this module through `<script type="module>`. If you're not using a build-system in your project, you can use the old-school `<script type="text/javascript" src="three-text2d.min.js" />` to load this file directly: https://github.com/gamestdio/three-text2d/blob/master/dist/three-text2d.min.js

And access `THREE_Text2D. SpriteText2D`, `THREE_Text2D. textAlign`, etc. Cheers!

**Comment by JoeriBultheel** [comment]
Hi endel! I'm learning step by step and am now running a build-system (I believe). I am using browsify for my js files but I still can't get the import statements to work. I am able to use require() now. Is there a way I can use require() for this library?

**Comment by endel** [comment]
@JoeriBultheel I'd recommend using `webpack` instead of `browserify`. 

You can probably find a lot of articles on the web about it, maybe this can be a starting point: 
- https://github.com/endel/babylonjs-multiplayer-boilerplate/tree/master/client
- https://github.com/endel/babylonjs-multiplayer-boilerplate/tree/master/client/webpack.config.js

cheers!

**Comment by JoeriBultheel** [comment]
@endel Thank you for the informative links! 
I was hoping to be able to do this with npm scripts alone... 
But I guess it's time to learn webpack.
thnx!
