### ISSUE TITLE
 How to change the font 

### ISSUE THREAD

**Issue by MachiBarton** [gamestdio/three-text2d#34]
I read the previous issue and used your method to modify the font, but there was no change, just changed to my default font. Would you like to ask if there are other ways to change the font?

**Comment by endel** [comment]
@MachiBarton change `"FontName"` by the name of the font you'd like to use. 

```
var text = new SpriteText2D(data.text, {
  font: "30px FontName",
})
```

If you're using a custom font, you may need to use this trick to pre-load it: https://github.com/gamestdio/three-text2d/issues/6#issuecomment-214025603
