### ISSUE TITLE
0.5.1 on npm same as 0.5.0

### ISSUE THREAD

**Issue by axion014** [gamestdio/three-text2d#38]
I have no idea what has led to this but it doesn't include what it says it does.
Given that we can't overwrite a npm version only options I think left is to unpublish it.
I hope you can make it work.

**Comment by axion014** [comment]
With 0.5.2 this is less of a problem, but it's not fixed so I'm keeping this open.

**Comment by endel** [comment]
Hi @axion014, what's not included on the latest version? 👀

**Comment by axion014** [comment]
Latest version is fine, just saying that 0.5.1 is corrupted.

**Comment by endel** [comment]
Perfect, thanks, I've just deprecated the version 0.5.1 :) Thanks for letting me know!
