### ISSUE TITLE
Centering text

### ISSUE THREAD

**Issue by russplaysguitar** [gamestdio/three-text2d#4]
Is there a recommended way to center text within the Text2d mesh? 

I see that text is always left-aligned within the Text2d canvas due to this line: https://github.com/gamestdio/three-text2d/blob/master/src/CanvasText.js#L32

I was able to center the text by changing the line to: `this.ctx.fillText(text, (this.canvas.width - this.textWidth)/2, (this.canvas.height - this.textHeight)/2);` but then there's no way to change that alignment either. 

Thanks

**Comment by endel** [comment]
Hey @russplaysguitar, using `textAlign.center` should do it. Example: https://github.com/gamestdio/three-text2d/blob/master/index.html#L37

**Comment by russplaysguitar** [comment]
I think that the problem was that I was scaling-up the text using `Text2d.geometry.scale()`, but this didn't scale-up the relative positioning of the text to the mesh. Using `Text2d.scale.multiplyScalar()` fixed that.
