### ISSUE TITLE
Request for TypeScript typings

### ISSUE THREAD

**Issue by webprofusion-chrisc** [gamestdio/three-text2d#9]
It would be great to have TypeScript typings for this library, published through https://github.com/typings/registry or Definitely Typed.

**Comment by endel** [comment]
@webprofusion-chrisc that would be great indeed. I'm using TypeScript in some projects and it is definitely great. I'll try to rewrite this lib during the weekend. Cheers!

**Comment by endel** [comment]
Hey @webprofusion-chrisc, this should be fine now. Just rewrote the entire lib in TypeScript and added [`typings` key on `package.json`](https://github.com/gamestdio/three-text2d/blob/211400bf79dbb6026abb9bd5bc6861dda1f67ad2/package.json#L5-L6).

Cheers!
